/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    InputText: typeof import('./components/InputText.vue')['default']
    Timer: typeof import('./components/Timer.vue')['default']
    Todo: typeof import('./components/Todo.vue')['default']
  }
}
